comment: off

ignore:
  - ".*/[Tt]ests/.*"
  - ".*/[Tt]est/.*"
  - "^docs"
  - "^container"

coverage:
  status:
    project:
      default:
        unittest:
        threshold: 0.03
    patch:
      default:
        target: 0
